// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kslxgjkhbtzxmxkmcdrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbHhnamtoYnR6eG14a21jZHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjMwODIsImV4cCI6MjA2MzI5OTA4Mn0.9d36vErVFfufGCbhrR9fi3PGjFbntmZBUFhj1xUEEa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);